{% set name = "jaraco.classes" %}
{% set version = "2.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "dcc2c4a8ca4b344cdbf2e1be7124a5c4f192574cdbb453b62350ae8240a2caf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python
    - six

test:
  imports:
    - jaraco
    - jaraco.classes

about:
  home: https://github.com/jaraco/jaraco.classes
  # license_file: jaraco doesn't include license files - see https://github.com/jaraco/skeleton/issues/1
  license: MIT
  license_family: MIT
  summary: 'jaraco.classes'
  dev_url: https://github.com/jaraco/jaraco.classes

extra:
  recipe-maintainers:
    - pmlandwehr
